# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/rest-clients.json
RestClients:
  SampleRestClient:
    UUID: 4a4f321f-73ae-4da3-be66-e35cf38b0b50
    Url: ${ivy.var.com.axonivy.solutions.process-analyser.demo.restUrl}
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
