# yaml-language-server: $schema=https://json-schema.axonivy.com/app/13.1.0/rest-clients.json
RestClients:
  testClient:
    UUID: 6d5fcdba-edcc-43e2-89ec-4c81a4f9c525
    Url: http://localhost:8081/
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
