# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/rest-clients-1.json
RestClients:
  testClient:
    Name: testClient
    Url: http://localhost:8081/
    Features:
      - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    LegacyUUID: 6d5fcdba-edcc-43e2-89ec-4c81a4f9c525
