package com.axonivy.solutions.process.analyser.core.enums;

public enum ElementType {
  REQUEST_START, SIGNAL_START_EVENT, TASK_END, ALTERNATIVE, SCRIPT, SCRIPT_BPMN_ELEMENT, SERVICE_BPMN_ELEMENT,
  EMBEDDED_PROCESS_ELEMENT, EMBEDDED_START, EMBEDDED_END, CALL_SUB_START, CALL_SUB_END, SUB_PROCESS_CALL,
  TASK_SWITCH_EVENT, TASK_SWITCH_GATEWAY, REST_CLIENT_CALL, ELEMENT;
}
