name: Dev-Deploy-Build

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/dev.yml@v5
    with:
      ivyVersion: 12
      ivyPluginVersion: 12.0.0
      testerVersion: 12.0.1

  deploy:
    needs: build
    runs-on: 'bpmn-statistic'
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            pom.xml
          sparse-checkout-cone-mode: false

      - name: Download artifact
        uses: actions/download-artifact@v4

      - name: Copy file
        run: |
          version=$(xml sel -t -m "//_:project" -v _:version pom.xml)
          artifactDir=artifact/process-analyser
          engineDeployDir=/var/tools/ivy/11/deploy/PROCESS-ANALYSER
          install -m 666 ${artifactDir}/target/process-analyser-${version}.iar $engineDeployDir/process-analyser-${version}.iar
          install -m 666 ${artifactDir}-demo/target/process-analyser-demo-${version}.iar $engineDeployDir/process-analyser-demo-${version}.iar

      - name: Restart engine
        run: |
          cd /etc/docker-compose/engine/11
          docker compose restart